### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by bensonkb** [appditto/natrium-wallet-server#1]
Got this error
```
[1552494902] Starting NatriumCast Server...
Traceback (most recent call last):
  File "natriumcast.py", line 919, in <module>
    print(os.path.join(cert_dir, cert_crt_file), os.path.join(cert_dir, cert_key_file))
  File "/root/natrium-wallet-server/venv/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by bbedward** [comment]
Hi,

You need to set the environment variables pointing to the certificates. Readme describes how to generate these using certbot

export NANO_KEY_FILE=privkey.pem
export NANO_CRT_FILE=fullchain.pem

There's no way to configure it to run without https currently, although I think recommended deployment will probably change to running behind a reverse proxy soon.
